export interface SpeechLanguage {
  code: string;
  nameEn: string;
  native: string;
}

export const SPEECH_LANGUAGES: SpeechLanguage[] = [
  { code: "af", nameEn: "Afrikaans", native: "Afrikaans" },
  { code: "am", nameEn: "Amharic", native: "አማርኛ" },
  { code: "ar", nameEn: "Arabic", native: "العربية" },
  { code: "as", nameEn: "Assamese", native: "অসমীয়া" },
  { code: "az", nameEn: "Azerbaijani", native: "Azərbaycan" },
  { code: "ba", nameEn: "Bashkir", native: "Башҡортса" },
  { code: "be", nameEn: "Belarusian", native: "Беларуская" },
  { code: "bg", nameEn: "Bulgarian", native: "Български" },
  { code: "bn", nameEn: "Bengali", native: "বাংলা" },
  { code: "bo", nameEn: "Tibetan", native: "བོད་སྐད" },
  { code: "br", nameEn: "Breton", native: "Brezhoneg" },
  { code: "bs", nameEn: "Bosnian", native: "Bosanski" },
  { code: "ca", nameEn: "Catalan", native: "Català" },
  { code: "cs", nameEn: "Czech", native: "Čeština" },
  { code: "cy", nameEn: "Welsh", native: "Cymraeg" },
  { code: "da", nameEn: "Danish", native: "Dansk" },
  { code: "de", nameEn: "German", native: "Deutsch" },
  { code: "el", nameEn: "Greek", native: "Ελληνικά" },
  { code: "en", nameEn: "English", native: "English" },
  { code: "es", nameEn: "Spanish", native: "Español" },
  { code: "et", nameEn: "Estonian", native: "Eesti" },
  { code: "eu", nameEn: "Basque", native: "Euskara" },
  { code: "fa", nameEn: "Persian", native: "فارسی" },
  { code: "fi", nameEn: "Finnish", native: "Suomi" },
  { code: "fo", nameEn: "Faroese", native: "Føroyskt" },
  { code: "fr", nameEn: "French", native: "Français" },
  { code: "gl", nameEn: "Galician", native: "Galego" },
  { code: "gu", nameEn: "Gujarati", native: "ગુજરાતી" },
  { code: "ha", nameEn: "Hausa", native: "Hausa" },
  { code: "haw", nameEn: "Hawaiian", native: "ʻŌlelo Hawaiʻi" },
  { code: "he", nameEn: "Hebrew", native: "עברית" },
  { code: "hi", nameEn: "Hindi", native: "हिन्दी" },
  { code: "hr", nameEn: "Croatian", native: "Hrvatski" },
  { code: "ht", nameEn: "Haitian Creole", native: "Kreyòl ayisyen" },
  { code: "hu", nameEn: "Hungarian", native: "Magyar" },
  { code: "hy", nameEn: "Armenian", native: "Հայերեն" },
  { code: "id", nameEn: "Indonesian", native: "Bahasa Indonesia" },
  { code: "is", nameEn: "Icelandic", native: "Íslenska" },
  { code: "it", nameEn: "Italian", native: "Italiano" },
  { code: "ja", nameEn: "Japanese", native: "日本語" },
  { code: "jw", nameEn: "Javanese", native: "Basa Jawa" },
  { code: "ka", nameEn: "Georgian", native: "ქართული" },
  { code: "kk", nameEn: "Kazakh", native: "Қазақша" },
  { code: "km", nameEn: "Khmer", native: "ខ្មែរ" },
  { code: "kn", nameEn: "Kannada", native: "ಕನ್ನಡ" },
  { code: "ko", nameEn: "Korean", native: "한국어" },
  { code: "la", nameEn: "Latin", native: "Latina" },
  { code: "lb", nameEn: "Luxembourgish", native: "Lëtzebuergesch" },
  { code: "ln", nameEn: "Lingala", native: "Lingála" },
  { code: "lo", nameEn: "Lao", native: "ລາວ" },
  { code: "lt", nameEn: "Lithuanian", native: "Lietuvių" },
  { code: "lv", nameEn: "Latvian", native: "Latviešu" },
  { code: "mg", nameEn: "Malagasy", native: "Malagasy" },
  { code: "mi", nameEn: "Maori", native: "Māori" },
  { code: "mk", nameEn: "Macedonian", native: "Македонски" },
  { code: "ml", nameEn: "Malayalam", native: "മലയാളം" },
  { code: "mn", nameEn: "Mongolian", native: "Монгол" },
  { code: "mr", nameEn: "Marathi", native: "मराठी" },
  { code: "ms", nameEn: "Malay", native: "Bahasa Melayu" },
  { code: "mt", nameEn: "Maltese", native: "Malti" },
  { code: "my", nameEn: "Myanmar", native: "မြန်မာ" },
  { code: "ne", nameEn: "Nepali", native: "नेपाली" },
  { code: "nl", nameEn: "Dutch", native: "Nederlands" },
  { code: "nn", nameEn: "Norwegian Nynorsk", native: "Nynorsk" },
  { code: "no", nameEn: "Norwegian", native: "Norsk" },
  { code: "oc", nameEn: "Occitan", native: "Occitan" },
  { code: "pa", nameEn: "Punjabi", native: "ਪੰਜਾਬੀ" },
  { code: "pl", nameEn: "Polish", native: "Polski" },
  { code: "ps", nameEn: "Pashto", native: "پښتو" },
  { code: "pt", nameEn: "Portuguese", native: "Português" },
  { code: "ro", nameEn: "Romanian", native: "Română" },
  { code: "ru", nameEn: "Russian", native: "Русский" },
  { code: "sa", nameEn: "Sanskrit", native: "संस्कृतम्" },
  { code: "sd", nameEn: "Sindhi", native: "سنڌي" },
  { code: "si", nameEn: "Sinhala", native: "සිංහල" },
  { code: "sk", nameEn: "Slovak", native: "Slovenčina" },
  { code: "sl", nameEn: "Slovenian", native: "Slovenščina" },
  { code: "sn", nameEn: "Shona", native: "chiShona" },
  { code: "so", nameEn: "Somali", native: "Soomaali" },
  { code: "sq", nameEn: "Albanian", native: "Shqip" },
  { code: "sr", nameEn: "Serbian", native: "Српски" },
  { code: "su", nameEn: "Sundanese", native: "Basa Sunda" },
  { code: "sv", nameEn: "Swedish", native: "Svenska" },
  { code: "sw", nameEn: "Swahili", native: "Kiswahili" },
  { code: "ta", nameEn: "Tamil", native: "தமிழ்" },
  { code: "te", nameEn: "Telugu", native: "తెలుగు" },
  { code: "tg", nameEn: "Tajik", native: "Тоҷикӣ" },
  { code: "th", nameEn: "Thai", native: "ไทย" },
  { code: "tk", nameEn: "Turkmen", native: "Türkmençe" },
  { code: "tl", nameEn: "Tagalog", native: "Tagalog" },
  { code: "tr", nameEn: "Turkish", native: "Türkçe" },
  { code: "tt", nameEn: "Tatar", native: "Татарча" },
  { code: "uk", nameEn: "Ukrainian", native: "Українська" },
  { code: "ur", nameEn: "Urdu", native: "اردو" },
  { code: "uz", nameEn: "Uzbek", native: "Oʻzbekcha" },
  { code: "vi", nameEn: "Vietnamese", native: "Tiếng Việt" },
  { code: "yi", nameEn: "Yiddish", native: "ייִדיש" },
  { code: "yo", nameEn: "Yoruba", native: "Yorùbá" },
  { code: "yue", nameEn: "Cantonese", native: "粵語" },
  { code: "zh", nameEn: "Chinese", native: "中文" },
];

export function speechLanguageOptions(
  autoLabel: string,
  locale: string,
  current?: string,
): Array<{ value: string; label: string }> {
  const named = SPEECH_LANGUAGES.map((item) => ({
    value: item.code,
    label: locale.startsWith("ru")
      ? `${item.native} (${item.code})`
      : `${item.nameEn} (${item.code})`,
  })).sort((a, b) => a.label.localeCompare(b.label, locale, { sensitivity: "base" }));
  const options = [{ value: "auto", label: autoLabel }, ...named];
  if (current && current !== "auto" && !options.some((item) => item.value === current)) {
    options.push({ value: current, label: current });
  }
  return options;
}
